import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    width: '100%',
    height: '100%',
  },
  container: {
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingBottom: 10,
  },
  header: {
    height: '11%',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
    paddingTop: 15,
    backgroundColor: 'white',
    paddingHorizontal: 15,
  },
  backButtonContainer: {
    height: 40,
    width: 40,
    borderRadius: 40 / 2,
    backgroundColor: '#044722',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainText: {
    fontSize: 20,
    fontWeight: '400',
    color: 'black',
    marginBottom: 15,
  },
  mainText2: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
  },
  containerStyle: {
    width: '90%',
  },
  contentContainerStyle: {
    backgroundColor: 'white',
    borderWidth: 0.2,
    width: '100%',
    paddingHorizontal: 15,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderColor: 'gray',
    paddingVertical: 15,
  },
  subLabel: {
    color: '#242e2a',
    fontSize: 14,
    marginBottom: 7,
  },
  checkBoxLabel: {
    color: '#242e2a',
    fontSize: 16,
    marginLeft: 6,
  },
  profilePictureView: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 20,
  },
  changeButton: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 15,
    borderRadius: 6,
    backgroundColor: '#044722',
  },
  buttonLabel: {
    color: 'white',
    fontSize: 16,
  },
  removeButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#044722',
  },
  buttonLabel1: {
    color: '#044722',
    opacity: 0.7,
    fontSize: 16,
  },
  profileTextInput: {
    width: '100%',
    borderWidth: 1,
    borderColor: 'gray',
    paddingVertical: 5,
    paddingHorizontal: 5,
    marginBottom: 20,
    borderRadius: 8,
  },
  checkBoxContainer: {
    width: '100%',
    marginBottom: 30,
  },
  checkBoxRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 10,
  },
  unselected: {
    height: 15,
    width: 15,
    borderWidth: 1,
    borderColor: '#044722',
  },
  selected: {
    height: 15,
    width: 15,
    borderWidth: 1,
    borderColor: '#044722',
    backgroundColor: '#044722',
  },
  logOutButton: {
    width: '100%',
    paddingVertical: 8,
    borderWidth: 1,
    borderRadius: 6,
    backgroundColor: '#fced65',
    borderColor: '#bfad08',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  bottomButtonContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  discardButton: {
    width: '40%',
    paddingVertical: 7,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 6,
    borderColor: '#044722',
    marginRight: 15,
  },
  saveButton: {
    width: '40%',
    paddingVertical: 7,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 6,
    borderColor: '#044722',
    backgroundColor: '#044722',
  },
});

export default styles;
